// ─────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit this file manually.
// Run  npm run sync  to regenerate from Google Sheets.
// ─────────────────────────────────────────────────────────

import type { ChapterContent } from "./content";

export const generatedContent: Record<string, ChapterContent> = {};
